### ISSUE TITLE
Get .app if not found locally from Package Manager

### ISSUE THREAD

**Issue by kine** [kine/NVRAppDevOps#1]
There is missing process for pulling .app from package manager if it is missing during compile or install process.

Support function Install-ALNugetPackage already exists, but is not used. 
Possibility to define own process for downloading missing app in settings.ps1 will be welcome - variable AppDownloadScript is prepared in the config for this.

**Comment by andreasblueher** [comment]
Hey Kamil, 

still working on a reply for the other PR. Since you talked about a package manager there I tried to google and find out what you mean. I wasn't successful maybe you could shed some light on this topic. Since it seems we'll need something like this anyway I'm willing to work on this.

**Comment by kine** [comment]
I will try to write some blog article if time allows. The support is now finished and you can use own script in AppDownloadScript setting to download missing dependency. 

Basic thing: from CI/CD you can now save any file as universal package to your Artifact server (Azure DevOps) and than download it from there when needed (I do not know how to do that through owershell yet). But I am using the nuget package for this - see New-ALNuSpec, New-ALNugetPackage, Push-ALNugetPackage and Install-ALnugetPackage cmdlets).
