### ISSUE TITLE
CALTestResults Webservice page

### ISSUE THREAD

**Issue by andreasblueher** [kine/NVRAppDevOps#10]
Hey Kamil,

after running a build using your template the CALTestResults Page 130405 is available as a web service, because it has been added to the Web Services Page. I've created a bc container manually with "importtesttoolkit" and the page is not available as a web service page, it exists though.

Is there some magic happening to add the page to Web Services and can you point to me it? Else your Read-ALTestResult could not work, but it does 🤷‍♂️

**Comment by MJECloud** [comment]
The magic happens [here](https://github.com/kine/MSDyn365BC_AppTemplate/blob/5fe7dadc06b2e915135234bb148e045713f64ad7/TestApp/Data/WebServices.xml) 😊

@kine i would suggest to implement this in Init-ALEnviroment.

**Comment by kine** [comment]
As @MJECloud mentioned, it is created by the Test App when installed. I am considering to create the webservice as suggested in Init-ALEnvironment.

**Comment by andreasblueher** [comment]
Thank you @MJECloud & @kine 

I think it would be really nice to have that in Init-ALEnvironment, because else each test app needs to add that data. Also I would appriciate if you could also add the CodeCoverageResults Page, because I want to look into adding those results to Azure DevOps as well.

What do you think about that @kine ?

**Comment by MJECloud** [comment]
Created a PR for this.

**Comment by kine** [comment]
Should be fixed now.
