### ISSUE TITLE
Suggestion: Support for EnableCodeCop and FailOn

### ISSUE THREAD

**Issue by epernst** [kine/NVRAppDevOps#13]
The navcontainerhelper function Compile-AppInNavContainer have support for running the CodeCop analyzer and storing the output with the compiler output.

        [switch]$EnableCodeCop,
        [ValidateSet('none','error','warning')]
        [string]$FailOn = 'none'

Please enable this in Compile-ALProjectTree.ps1, so that we can get this information into DevOps. Very valuable for the code review.

**Comment by kine** [comment]
Released. Including the JSON setting support with profiles. Need to update the NaverticAl to support this.
