### ISSUE TITLE
New-WebServiceProxy ReadMultiple 404 not found

### ISSUE THREAD

**Issue by MJECloud** [kine/NVRAppDevOps#14]
Hello Kamil, 

in Read-ALTestResult we're getting an exception since updating our containers to spring release.

> Exception calling "ReadMultiple" with "3" argument(s): "The request failed with HTTP status 404: Not Found."

> $_.Exception.StackTrace
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

This doesnt seem to be related to your module but it effects it.
Do you get the same error? 

Thank you for your help.

**Comment by kine** [comment]
Please, try to use the new cmdlet Run-ALTestInContainer. It is using the Freddy's new tools to run the tests and export the data.

I am not using the old Run-ALTest and Read-ALTestResult which are used inside the Test-ALApp cmdlet.

The Run-ALTestInContainer is running the tests from within container through the standard Test Suite objects (and one page which is donwloaded automatically from within navcontainerhelper) and will give you directly the results as XUnit file.

If you cannot use these from any reason, just tell me and I will check what is the problem. May be something connected to the change in visibility of non-External functions within the last CUs.

May be the ReadMultiple function was changed and have different parameters...

**Comment by MJECloud** [comment]
Hello Kamil, 

thank you for your answer.
I tried Run-ALTestInContainer but it doesnt run the codeunit i want. 
Do you know if its necessary that the Codeunit is in the TestSuit?

**Comment by kine** [comment]
Yes, it is.

**Comment by MJECloud** [comment]
Ah ok, thank you! 
It works now.
