### ISSUE TITLE
Incorrect Ruleset Used in Compile with Artifact

### ISSUE THREAD

**Issue by skmcavoy** [kine/NVRAppDevOps#34]
Hello,

On following line, $containerRulesetFile should be $rulesetfile as that is what is passed into Compile-AppWithArtifact by param.

https://github.com/kine/NVRAppDevOps/blob/87edf8a69d6db8c8230eae25e88d93f3b5e3e5e3/NVRAppDevOps/Compile-AppWithArtifact.ps1#L151

**Comment by kine** [comment]
Fixed in commit c12b842, released as v2.0.44.
