### ISSUE TITLE
Error "There was no endpoint listening at http://localhost:7086/BC/ManagementServicePs/Service.svc that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details." when creating new container

### ISSUE THREAD

**Issue by kine** [kine/NVRAppDevOps#36]
There is error 
---
There was no endpoint listening at http://localhost:7086/BC/ManagementServicePs/Service.svc that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details.
---
When creating new container by using Init-ALEnvironment or through BCTask createbccontainer from https://marketplace.visualstudio.com/items?itemName=Kine.naverticaltasks (which is internally calling this function).

Reason was implicit using of '-e CustomNavSettings=ServicesUseNTLMAuthentication=true' parameter for the new-bccontainer cmdlet which makes the endpoint unusable. 

Solution: 
This implicit parameter was removed. If needed, optionalParameters could be used to set it again.
Connected to #1a624b5905f7ae85ea45a0439c170250069c2565

**Comment by kine** [comment]
Identified in https://github.com/microsoft/navcontainerhelper/issues/3202

**Comment by pmoisontech** [comment]
@kine Hi, do you know if the true value for this parameter (ServicesUseNTLMAuthentication) in no longer supported from BC23 or it's just a bug in the RTM?

**Comment by kine** [comment]
For me it should be bug because I cannot imagine why it should have effect like this. But because the focuse now is more on AAD (Entra ID) authentication and Windows auth have last year many problems with Kerberos delegation, I recommend to not use the windows auth in connection with containers at all.
