### ISSUE TITLE
Business Foundation app needs to be copied in v24 for Compile-AppWithArtifact

### ISSUE THREAD

**Issue by skmcavoy** [kine/NVRAppDevOps#39]
In Compile-AppWithArtifact, we need to copy the new Business Foundation app to the build folder like other MS core apps.

Adding to https://github.com/kine/NVRAppDevOps/blob/7d4173347d238d26064aa3ad206a2130f9c1c64b/NVRAppDevOps/Compile-AppWithArtifact.ps1#L48C2-L54C119
`    (Join-Path $AppPath "\Applications.*\Microsoft_Business Foundation_*.app"),`
resolves issue

**Comment by kine** [comment]
Thanks for reporting. I am going to add it there and think about possible generic solution for this, because more and more apps will be added like this from Microsoft. I hope that in short time we will be able to migrate e.g. to use NuGet packages to solve this.

**Comment by kine** [comment]
released in v2.7.0.

Thanks for reporting!
