### ISSUE TITLE
Cannot bind parameter because parameter 'publisher' is specified more than once.

### ISSUE THREAD

**Issue by antony-acumencentral** [kine/NVRAppDevOps#40]
Hi Kine,

I got below error when running Business Central - Compile App in Container. Usually, I don't have any issue using it in the pipeline until yesterday. 

[LogFiles.txt](https://github.com/kine/NVRAppDevOps/files/14535688/LogFiles.txt)

**Comment by sayanacumenau** [comment]
Hi Kine,

I think the issue stems from below script Compile-ALProjectTree and the line - 
Download-ALApp -name $App.name -publisher $App.publisher -publisher $App.id -version $App.version -targetPath $PackagesPath -AppDownloadScript $AppDownloadScript

There are two publisher parameter, I think the second one should be -id

**Comment by kine** [comment]
Yes, this seems wrong... will check.

**Comment by kine** [comment]
Can you test now with the prerelease version of v2.8.1 beta6?

**Comment by kine** [comment]
The problem should be solved now in v2.8.1. It was bug for situations where there were no app to download when calling Download-ALApp.

**Comment by sayanacumenau** [comment]
Thank you very much, yes it is solved now.
