### ISSUE TITLE
Using $env:TF_BUILD instead of $Build in Init-ALEnviroment

### ISSUE THREAD

**Issue by MJECloud** [kine/NVRAppDevOps#7]
Hello Kamil, 

is there a reason why you use $Build in Init-ALEnviroment
https://github.com/kine/NVRAppDevOps/blob/87e34a3495ef9969c7859cd5202d7d0848b3e099/Init-ALEnvironment.ps1#L61

instead of $env:TF_Build like you do in Compile-ALProjectTree? 
https://github.com/kine/NVRAppDevOps/blob/87e34a3495ef9969c7859cd5202d7d0848b3e099/Compile-ALProjectTree.ps1#L67

Greetings, 
Maurice

**Comment by kine** [comment]
Hi Maurice,
I think it is just historical reason, when I was in need to test the script manually but "simulate" running under agent (passing manually the flag). 

I have added Build flag enforcing when $env:TF_BUILD is set... 

See commit e987b4508f20ccaaa73644fc75ffe6358f0cd1d9

**Comment by MJECloud** [comment]
Hi Kamil, 

good to know 
Thank you! :)
